# non-existing pipeline id
@non-existing-pipeline-id = "0000000000000000000000"

###
# Get Hermes Health
GET {{codefresh-url}}/api/hermes/health

###
# Get Hermes Version
GET {{codefresh-url}}/api/hermes/version

###
# Ping Hermes
GET {{codefresh-url}}/api/hermes/ping

###
# Get Event Types
GET {{codefresh-url}}/api/hermes/types/?type=registry
Authorization: {{api-token}}

###
# Get DockerHub Event Type: type=registry kind=dockerhub
# Expected: 200
GET {{codefresh-url}}/api/hermes/types/registry/dockerhub
Authorization: {{api-token}}

###
# Get Non-existing Event Type: type=none kind=some
# Expected: 404
GET {{codefresh-url}}/api/hermes/events/types/none/some
Authorization: {{api-token}}

###
# Get Event Info details for DockerHub codefresh/fortune push event
# NOTE: create trigger pipeline before
GET {{codefresh-url}}/api/hermes/events/registry:dockerhub:codefresh:fortune:push
Authorization: {{api-token}}

###
# Get all triggers for pipeline 
#   pipeline: existing pipeline id
# NOTE: create trigger pipeline before
GET {{codefresh-url}}/api/hermes/triggers/{{existing-pipeline-id}}
Authorization: {{api-token}}

###
# Get all triggers for non-existing pipeline 
# NOTE: create trigger pipeline before
# Expected: 404
GET {{codefresh-url}}/api/hermes/triggers/{{non-existing-pipeline-id}}
Authorization: {{api-token}}

###
# Create trigger event - codefresh/fortune DockerHub push
POST {{codefresh-url}}/api/hermes/events
Content-Type: application/json
Authorization: {{api-token}}

["{{existing-pipeline-id}}"]

###
# Add pipeline - some existing pipeline
# to 
# trigger event - codefresh/fortune DockerHub push
POST {{codefresh-url}}/api/hermes/events
Content-Type: application/json
Authorization: {{api-token}}

{
	"type": "registry",
	"kind": "dockerhub",
	"secret": "123456789",
	"context": "dockerhub",
	"values": {
		"namespace": "codefresh",
		"name": "fortune"
	}
}

###
# Try adding non-existing pipeline
# to 
# trigger - codefresh/fortune DockerHub push
# Expected: 500
POST {{codefresh-url}}/api/hermes/events/trigger/registry:dockerhub:codefresh:fortune:push
Content-Type: application/json
Authorization: {{api-token}}

["{{non-existing-pipeline-id}}"]

###
# Delete pipeline
#   event: codefresh/fortune DockerHub push
#   pipeline: existing pipeline id
DELETE {{codefresh-url}}/api/hermes/triggers/registry:dockerhub:codefresh:fortune:push/pipelines/{{existing-pipeline-id}}
Authorization: {{api-token}}

###
# Try deleting non-existing pipeline
#   event: codefresh/fortune DockerHub push
#   pipeline: non-existing pipeline id
# Expected: 500
DELETE {{codefresh-url}}/api/hermes/triggers/registry:dockerhub:codefresh:fortune:push/pipelines/{{non-existing-pipeline-id}}
Authorization: {{api-token}}
