###
# Get Hermes Health
GET {{codefresh-url}}/api/hermes/health

###
# Get Hermes Version
GET {{codefresh-url}}/api/hermes/version

###
# Ping Hermes
GET {{codefresh-url}}/api/hermes/ping

###
# Get Event Types
GET {{codefresh-url}}/api/hermes/events/types
Authorization: {{api-token}}

###
# Get DockerHub Event Type: type=registry kind=dockerhub
GET {{codefresh-url}}/api/hermes/events/types/registry/dockerhub
Authorization: {{api-token}}

###
# Get Event Info details for DockerHub codefresh/fortune push event
# NOTE: create trigger pipeline before
GET {{codefresh-url}}/api/hermes/events/info/index.docker.io:codefresh:fortune:push
Authorization: {{api-token}}

###
# Get all triggers for pipeline 
#   pipeline: alexei-led codefresh-io/trigger-examples run_fortune
# NOTE: create trigger pipeline before
GET {{codefresh-url}}/api/hermes/triggers/alexei-led:codefresh-io:trigger-examples:run_fortune
Authorization: {{api-token}}

###
# Add pipeline - alexei codefresh-io/trigger-examples run_fortune
# to 
# trigger - codefresh/fortune DockerHub push
POST {{codefresh-url}}/api/hermes/triggers/index.docker.io:codefresh:fortune:push/pipelines
Content-Type: application/json
Authorization: {{api-token}}

[
	{
		"account": "alexei-led",
		"repo-owner": "codefresh-io", 
		"repo-name": "trigger-examples",
		"name": "run_fortunez"
	}
]

###
# Delete pipeline
#   event: codefresh/fortune DockerHub push
#   pipeline: alexei codefresh-io/trigger-examples run_fortune
DELETE {{codefresh-url}}/api/hermes/triggers/index.docker.io:codefresh:fortune:push/pipelines/alexei-led:codefresh-io:trigger-examples:run_fortune
Authorization: {{api-token}}
