dependencies:
  # trigger manager
  - name: hermes
    version: 0.3.1
    repository: alias:hermes
    tags:
      - trigger-manager
      - codefresh
  # dockerhub event provider
  - name: nomios
    version: 0.2.1
    repository: alias:hermes
    tags:
      - event-provider
      - dockerhub