dependencies:
  # trigger manager
  - name: hermes
    version: 0.7.0
    repository: alias:hermes
    tags:
      - trigger-manager
      - codefresh
  # dockerhub event provider
  - name: nomios
    version: 0.4.0
    repository: alias:hermes
    tags:
      - event-provider
      - dockerhub
    # dockerhub event provider
  - name: cronus
    version: 0.1.1
    repository: alias:hermes
    tags:
      - event-provider
      - cron