dependencies:
- name: redis
  version: 1.1.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  tags:
    - infra
- name: nomios
  version: 0.1.1
  repository: https://codefresh-io.github.io/hermes/
  tags:
    - event-provider
    - dockerhub
