// Code generated by mockery v1.0.0
package model

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, account, eventURI, event
func (_m *MockEventPublisher) Publish(ctx context.Context, account string, eventURI string, event NormalizedEvent) error {
	ret := _m.Called(ctx, account, eventURI, event)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, NormalizedEvent) error); ok {
		r0 = rf(ctx, account, eventURI, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
