// Code generated by mockery v1.0.0
package model

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockTriggerEventSubscriber is an autogenerated mock type for the TriggerEventSubscriber type
type MockTriggerEventSubscriber struct {
	mock.Mock
}

// UpdateEventSubscription provides a mock function with given fields: ctx, event, addActions, removeActions
func (_m *MockTriggerEventSubscriber) UpdateEventSubscription(ctx context.Context, event *Event, addActions []string, removeActions []string) (*EventInfo, error) {
	ret := _m.Called(ctx, event, addActions, removeActions)

	var r0 *EventInfo
	if rf, ok := ret.Get(0).(func(context.Context, *Event, []string, []string) *EventInfo); ok {
		r0 = rf(ctx, event, addActions, removeActions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EventInfo)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *Event, []string, []string) error); ok {
		r1 = rf(ctx, event, addActions, removeActions)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
