// Code generated by mockery v1.0.0
package model

import mock "github.com/stretchr/testify/mock"

// MockSecretChecker is an autogenerated mock type for the SecretChecker type
type MockSecretChecker struct {
	mock.Mock
}

// Validate provides a mock function with given fields: message, secret, key
func (_m *MockSecretChecker) Validate(message string, secret string, key string) error {
	ret := _m.Called(message, secret, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(message, secret, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
