// Code generated by mockery v1.0.0
package model

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockTriggerEventGetter is an autogenerated mock type for the TriggerEventGetter type
type MockTriggerEventGetter struct {
	mock.Mock
}

// GetEvent provides a mock function with given fields: ctx, event
func (_m *MockTriggerEventGetter) GetEvent(ctx context.Context, event string) (*Event, error) {
	ret := _m.Called(ctx, event)

	var r0 *Event
	if rf, ok := ret.Get(0).(func(context.Context, string) *Event); ok {
		r0 = rf(ctx, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Event)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
