// Code generated by mockery v1.0.0
package model

import mock "github.com/stretchr/testify/mock"

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

// Run provides a mock function with given fields: account, pipelines, vars, event
func (_m *MockRunner) Run(account string, pipelines []string, vars map[string]string, event NormalizedEvent) ([]PipelineRun, error) {
	ret := _m.Called(account, pipelines, vars, event)

	var r0 []PipelineRun
	if rf, ok := ret.Get(0).(func(string, []string, map[string]string, NormalizedEvent) []PipelineRun); ok {
		r0 = rf(account, pipelines, vars, event)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]PipelineRun)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, []string, map[string]string, NormalizedEvent) error); ok {
		r1 = rf(account, pipelines, vars, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
